"""
SARSP-LangEd - Legal Consent Gate
Privacy-first consent management with NO usage data collection.
"""

import streamlit as st
from datetime import datetime

# ============================================================================
# LEGAL TEXTS
# ============================================================================

TERMS_OF_USE = """
## Terms of Use — SARSP-LangEd Pipeline

**Last updated:** September 2026

### 1. Acceptance of Terms
By accessing and using the SARSP-LangEd (Semi-Automated Research Synthesis Protocol 
for Language Education) application, you agree to be bound by these Terms of Use. 
If you do not agree, please discontinue use immediately.

### 2. Purpose of the Tool
SARSP-LangEd is an open-source research methodology tool designed to assist 
researchers in conducting semi-automated systematic reviews in education. 
It is provided for **academic and research purposes only**.

### 3. User Responsibilities
You are solely responsible for:
- The **quality, legality, and appropriateness** of any data you upload.
- Ensuring you hold **legitimate access rights** (institutional subscriptions, 
  open-access licences, fair-use exemptions) to all uploaded documents.
- The **configuration choices** you make at each pipeline stage.
- The **verification** of all computational outputs against source documents.
- Compliance with applicable **institutional, national, and disciplinary regulations**.
- The **interpretive claims** you advance based on pipeline outputs.

### 4. No Warranty
The tool is provided "as is" without warranty of any kind. The developers make 
no guarantees regarding accuracy, completeness, or fitness for a particular purpose. 
All outputs are **provisional computational suggestions** requiring human verification.

### 5. Intellectual Property
- The SARSP-LangEd pipeline code is released under the **MIT License**.
- Uploaded documents remain the property of their original copyright holders.
- Outputs generated by the tool belong to the user.

### 6. Limitation of Liability
The developers shall not be liable for any damages arising from the use or 
inability to use this tool, including but not limited to data loss, 
incorrect outputs, or research decisions made based on tool outputs.

### 7. Third-Party Services
This tool may connect to third-party LLM APIs (e.g., Mistral AI, OpenAI, 
Google Gemini, Cerebras). Your use of these services is governed by their 
respective terms of service and privacy policies. API keys are processed 
locally and are **never stored or transmitted** to the SARSP-LangEd developers.

### 8. Modifications
These terms may be updated periodically. Continued use after updates 
constitutes acceptance of the revised terms.

### 9. Contact
For questions regarding these terms, contact the corresponding author 
at the email provided in the associated publication.
"""

PRIVACY_POLICY = """
## Privacy Policy — SARSP-LangEd Pipeline

**Last updated:** September 2026

### 1. Our Commitment: No Data Collection
SARSP-LangEd is designed as a **privacy-first** application. We do **not** collect, 
store, or transmit any personal data or usage analytics.

### 2. What We Do NOT Collect
We do **not** collect any of the following:
- Personal identifiers (name, email, institution, IP address)
- Content of uploaded files (PDFs, JSON, CSV, Excel)
- API keys or credentials
- Text of prompts or extracted data
- Usage analytics (which stages you visit, how long you spend, etc.)
- Cookies or tracking scripts

### 3. How Your Data Is Handled
- **Session data**: Any data you upload (PDFs, JSON files, API keys) exists only 
  in your browser session and is stored temporarily on Streamlit's servers for the 
  duration of your session. This data is **automatically deleted** when your session 
  ends or times out.
- **No persistence**: We do not maintain databases, logs, or backups of user sessions.
- **No third-party sharing**: Your data is never shared with third parties 
  (except the LLM API providers you explicitly configure, whose own privacy 
  policies apply).

### 4. What We DO Track (Only via Streamlit Cloud)
The only metrics available to the developers are those provided by Streamlit Cloud's 
native dashboard, which includes:
- Aggregate viewer count (number of unique visitors)
- Aggregate session duration
These metrics are **anonymous, aggregated, and cannot be linked to individual users**.

### 5. Legal Basis
Since we do not collect personal data, no legal basis under GDPR or similar 
regulations is required for data processing.

### 6. Your Rights
Since we do not collect data, there is no data to access, erase, or port. 
If you have concerns about data held by Streamlit Cloud (the hosting provider), 
please refer to [Streamlit's Privacy Policy](https://streamlit.io/privacy-policy).

### 7. Children's Data
This tool is intended for researchers and is not directed at individuals 
under 16.

### 8. Changes to This Policy
Updates will be posted here with a revised date.
"""

# ============================================================================
# CONSENT MANAGEMENT
# ============================================================================

def is_consent_given() -> bool:
    """Check if user has accepted required consents."""
    return (
        st.session_state.get("consent_terms", False)
        and st.session_state.get("consent_privacy", False)
    )


def set_consent(terms: bool, privacy: bool):
    """Record consent decisions in session state."""
    st.session_state["consent_terms"] = terms
    st.session_state["consent_privacy"] = privacy
    st.session_state["consent_timestamp"] = datetime.now().isoformat()


# ============================================================================
# CONSENT GATE UI
# ============================================================================

def render_consent_gate():
    """Render the consent gate. Returns True if consent is given."""
    
    if is_consent_given():
        return True
    
    st.markdown("""
    <style>
    .consent-container {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
        border: 2px solid #4CAF50;
        border-radius: 12px;
        background-color: #f9fff9;
    }
    .consent-header {
        text-align: center;
        margin-bottom: 1.5rem;
    }
    .legal-box {
        max-height: 300px;
        overflow-y: auto;
        border: 1px solid #ddd;
        border-radius: 8px;
        padding: 1rem;
        margin: 1rem 0;
        background: white;
        font-size: 0.9rem;
    }
    </style>
    """, unsafe_allow_html=True)
    
    st.markdown('<div class="consent-container">', unsafe_allow_html=True)
    
    st.markdown("""
    <div class="consent-header">
    
    ## 📚 SARSP-LangEd Pipeline
    
    ### Semi-Automated Research Synthesis Protocol for Language Education
    
    **Before using this tool, please review and accept the following:**
    
    </div>
    """, unsafe_allow_html=True)
    
    st.divider()
    
    # --- Terms of Use ---
    st.markdown("### 📋 Terms of Use")
    st.markdown('<div class="legal-box">', unsafe_allow_html=True)
    st.markdown(TERMS_OF_USE)
    st.markdown('</div>', unsafe_allow_html=True)
    
    terms_check = st.checkbox(
        "I have read and accept the **Terms of Use** *",
        key="gate_terms_check"
    )
    
    st.divider()
    
    # --- Privacy Policy ---
    st.markdown("### 🔒 Privacy Policy")
    st.markdown('<div class="legal-box">', unsafe_allow_html=True)
    st.markdown(PRIVACY_POLICY)
    st.markdown('</div>', unsafe_allow_html=True)
    
    privacy_check = st.checkbox(
        "I have read and accept the **Privacy Policy** *",
        key="gate_privacy_check"
    )
    
    st.divider()
    
    # --- Submit ---
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        accept_btn = st.button(
            "✅ Accept and Continue",
            type="primary",
            use_container_width=True,
            disabled=not (terms_check and privacy_check),
            key="gate_accept_btn"
        )
    
    if not (terms_check and privacy_check):
        st.caption("⚠️ You must accept both the Terms of Use and Privacy Policy to proceed.")
    
    st.markdown('</div>', unsafe_allow_html=True)
    
    if accept_btn and terms_check and privacy_check:
        set_consent(True, True)
        st.rerun()
    
    return False


def render_consent_footer():
    """Render a small footer link to review consent/legal docs."""
    st.divider()
    with st.expander("📋 Legal: Terms of Use & Privacy Policy"):
        tab_terms, tab_privacy = st.tabs(["Terms of Use", "Privacy Policy"])
        with tab_terms:
            st.markdown(TERMS_OF_USE)
        with tab_privacy:
            st.markdown(PRIVACY_POLICY)
        
        # Show current consent status
        st.markdown("---")
        st.markdown("**Your consent status:**")
        st.markdown(f"- Terms accepted: {'✅' if st.session_state.get('consent_terms') else '❌'}")
        st.markdown(f"- Privacy accepted: {'✅' if st.session_state.get('consent_privacy') else '❌'}")
        if st.session_state.get('consent_timestamp'):
            st.markdown(f"- Consent given: {st.session_state['consent_timestamp'][:19]}")